### ISSUE TITLE
Parenthesis Bug

### ISSUE THREAD

**Issue by mechatronic3000** [QB64-Phoenix-Edition/QB64pe#205] opened 2022-10-03 09:56 UTC
I found a minor bug in the syntax checking for the IDE. 

If for some reason you put parenthesis around a single argument to a sub that is an array, the IDE wont report an syntax error, instead you will get a cryptic compilation error. The bug can be repeated with the following code.

This is as of version 3.1 and I'm running on Linux Mint 19.1

`'Parenthesis Bug

DIM t(5) AS LONG

test t()
test (t()) ' Compile Error not a Syntax Error

'test2 t(), 0
'test2(t(),0) ' Uncomment for Syntax error

SUB test (t() AS LONG)
  t(0) = t(0) ' clear warning
END SUB

SUB test2 (t() AS LONG, tt AS LONG)
  t(0) = tt ' clear warning
END SUB`

Compilelog.txt contains.

`g++ -O2 -no-pie -w -std=gnu++11 -DFREEGLUT_STATIC -I./internal/c/libqb/include -DDEPENDENCY_NO_SOCKETS -DDEPENDENCY_NO_PRINTER -DDEPENDENCY_NO_ICON -DDEPENDENCY_NO_SCREENIMAGE internal/c/qbx.cpp -c -o internal/c/qbx.o
In file included from internal/c/qbx.cpp:2570:0:
internal/c/../temp/maindata.txt: In function ‘void QBMAIN(void*)’:
internal/c/../temp/maindata.txt:13:2: error: ‘pass1’ was not declared in this scope
  pass1;
  ^~~~~
internal/c/../temp/maindata.txt:13:2: note: suggested alternative: ‘pause’
  pass1;
  ^~~~~
  pause
Makefile:375: recipe for target 'internal/c/qbx.o' failed
make: *** [internal/c/qbx.o] Error 1`

Maindata.txt contains.

`if (!__ARRAY_LONG_T){
__ARRAY_LONG_T=(ptrszint*)mem_static_malloc(9*ptrsz);
new_mem_lock();
mem_lock_tmp->type=4;
((ptrszint*)__ARRAY_LONG_T)[8]=(ptrszint)mem_lock_tmp;
__ARRAY_LONG_T[4]= 0 ;
__ARRAY_LONG_T[5]=( 5 )-__ARRAY_LONG_T[4]+1;
__ARRAY_LONG_T[6]=1;
__ARRAY_LONG_T[0]=(ptrszint)mem_static_malloc(__ARRAY_LONG_T[5]*4);
memset((void*)(__ARRAY_LONG_T[0]),0,__ARRAY_LONG_T[5]*4);
__ARRAY_LONG_T[2]=1+2;
}
 pass1;`

**Comment by mkilgore** [comment] 2022-10-03 11:36
I think you're hitting #118, which isn't yet fixed. But basically it's not a syntax error, it's supposed to pass the array by value (make a copy and send that to the sub/function) but it doesn't work correctly.

That said I can't tell from #118 if I checked that QB45 works this way or I just assumed, if it doesn't support this then potentially we could just say it's bad syntax rather than fix it. Passing an array by value isn't really super useful TBH, it certainly has some uses but arrays are usually pretty big to be copying all the time.

**Comment by mechatronic3000** [comment] 2022-10-03 20:50
I ran into this error when I was refactoring one of my older programs and removing 'CALL' statements. Something I wasn't aware I could do early on.

`CALL Somesub( arg() ) ---> Somesub arg()`

So, I used search and replace to delete the CALL keywords, and then remove the parenthesis by hand. I was relying on the IDE to point out the syntax errors(extra parenthesis), and I would remove them. It did not catch a single argument SUB, thus my error.

`test t()`
`test (t()) ' Compile Error not a Syntax Error`

`test2 t(), 0`
`test2 (t(),0) '  Syntax error`

Well, if it were up to me, I would make it consistent with a multi-argument sub and generate a syntax error. I like the idea of being able to choose if arguments are passed by reference or by value, but in my mind, a keyword would be more concise, for example  'byval' or 'byref'. 

Thanks

**Comment by mkilgore** [comment] 2022-10-03 21:03
>  I like the idea of being able to choose if arguments are passed by reference or by value, but in my mind, a keyword would be more concise, for example 'byval' or 'byref'.

Yeah I can understand that thinking, unfortunately we're stuck with that syntax since that's how QBasic did it. Non-array arguments work the same way (barring a separate bug with strings 🤦), so `test (int)` passes a copy of the integer variable `int`. You might want to check for that one since that won't trigger a compilation error.

**Comment by mkilgore** [comment] 2022-10-07 02:36
Duplicate of #118

**Closed** 2022-10-07 02:37 UTC
