### ISSUE TITLE
Idea!  Add Arrays to Types

### ISSUE THREAD

**Issue by TheXadGaming** [QB64-Phoenix-Edition/QB64pe#354] opened 2023-06-28 12:28 UTC
I'm not new to programming, but I'm not super advanced. So there may be a better way to format things in code.
Doing this:
`Type Example`
`     Paramter1 As Integer`
`     Paramter2 As Integer`
`     Paramter3(10) As Integer`
`End Type`
Doesn't work, you can't have an array in types.
Maybe there is a way to do this better without types, or maybe there already is a way to do this that I'm missing.

**Comment by mechatronic3000** [comment] 2023-06-28 12:53
I ran into a similar issue with my 2d physics engine. What I ended up doing is making the arrays into _MEM's (essentially making it a pointer) and I created some getters and setters to extract my data from the _MEM array.

Here is an example of what I did. You can make "test" and array in itself, however you have to do a _memnew for each element in the array.

`TYPE Example
  Parameter1 AS INTEGER
  Parameter2 AS INTEGER
  Parameter3 AS _MEM
END TYPE

DIM test AS Example: test.Parameter3 = _MEMNEW(2 * 10) ' sizeof Integer * Number of elements

setter test, 2, 5
setter test, 6, 3
setter test, 9, 1

PRINT getter(test, 2)
PRINT getter(test, 6)
PRINT getter(test, 9)

SUB setter (test AS Example, index AS LONG, value AS INTEGER)
  _MEMPUT test.Parameter3, test.Parameter3.OFFSET + (index * 2), value AS INTEGER
END SUB

FUNCTION getter% (test AS Example, index AS LONG)
  getter = _MEMGET(test.Parameter3, test.Parameter3.OFFSET + (index * 2), INTEGER)
END FUNCTION
`

**Comment by TheXadGaming** [comment] 2023-06-28 13:33
Thank you for the help! I haven't experimented much with Memory and stuff, so I have a new project to work on.

**Comment by a740g** [comment] 2023-06-28 16:51
> I'm not new to programming, but I'm not super advanced. So there may be a better way to format things in code. Doing this: `Type Example` ` Paramter1 As Integer` ` Paramter2 As Integer` ` Paramter3(10) As Integer` `End Type` Doesn't work, you can't have an array in types. Maybe there is a way to do this better without types, or maybe there already is a way to do this that I'm missing.

This is already in our list: #135 

> I ran into a similar issue with my 2d physics engine. What I ended up doing is making the arrays into _MEM's (essentially making it a pointer) and I created some getters and setters to extract my data from the _MEM array.

Yeah. That is a good workaround, but IMO is a bit clumsy, and it forces you to do the initialization, cleanup and use the weird _MEMGET, _MEMPUT syntax. 😄

**Comment by mechatronic3000** [comment] 2023-06-28 20:51
> Yeah. That is a good workaround, but IMO is a bit clumsy, and it forces you to do the initialization, cleanup and use the weird _MEMGET, _MEMPUT syntax. smile

Well, If your not happy about that method then you could also try the string method.

`
TYPE Example
  Parameter1 AS INTEGER
  Parameter2 AS INTEGER
  Parameter3 AS STRING * 22 ' (sizeof Integer * Number of elements) + sizeof Integer
END TYPE

DIM test AS Example

setter test.Parameter3, 1, 5
setter test.Parameter3, 6, 3
setter test.Parameter3, 10, 1

PRINT getter(test.Parameter3, 1)
PRINT getter(test.Parameter3, 6)
PRINT getter(test.Parameter3, 10)

FUNCTION getter% (s AS STRING, p AS LONG)
  IF p > 0 AND p * 2 + 2 <= LEN(s) THEN getter = CVI(MID$(s, p * 2, 2))
END FUNCTION

SUB setter (s AS STRING, p AS LONG, v AS INTEGER)
  IF p > 0 AND p * 2 + 2 <= LEN(s) THEN MID$(s, p * 2) = MKI$(v)
END SUB
`

This one has a couple of things to accommodate for. You strings are probably going to be fixed length, so no growing the array runtime. Two no zero index.

**Comment by flukiluke** [comment] 2024-06-30 14:06
Closing as duplicate of #135

**Closed by flukiluke** 2024-06-30 14:06 UTC
