### ISSUE TITLE
Search freezes program in Ubuntu

### ISSUE THREAD

**Issue by loopy750** [QB64-Phoenix-Edition/QB64pe#57] opened 2022-05-15 15:53 UTC
Simple to reproduce (hopefully). Open program and press F3 to search. Freezes and requires xkill to force close it.

**Comment by SteveMcNeill** [comment] 2022-05-15 16:50
Is this the latest version 0.6?  Or a pull direct from the repo?  We're currently working on an issue in the repo and suggest everyone stick to the official releases for now.

**Comment by loopy750** [comment] 2022-05-15 16:52
It is the latest, v0.6.0.

The QB64Team version, v2.0.2, I can't reproduce this bug.

Thanks.

**Comment by mkilgore** [comment] 2022-05-16 06:20
Unfortunately I did try this but was unable to reproduce it. Can you try reproducing it with the Linux artifact from [this build](https://github.com/QB64-Phoenix-Edition/QB64pe/actions/runs/2328402995)? Just download the `qb64-lnx-x64` artifact listed near the bottom, it's a `zip` and the typical Linux distribution `.tar.gz` file is inside.

If it does still happen, could you create a core dump of the process for us to see? You should be able to just do `gcore PID` to make one (where `PID` is the process ID of the QB64 executable). You might need to install a package to get `gcore` but I think you probably already have it.

**Comment by loopy750** [comment] 2022-05-16 07:48
Thanks, but it's the same with that build.

I don't know much about Linux. I'm normally using windows, I just wanted to create a linux version, which worked fine. I've been using Virtualbox, so I tested Ubuntu natively to make sure that wasn't the issue, and it still freezes.

Steps were straight forward: load Ubuntu from USB, open Firefox to download and QB64 Phoenix. Press F3 to trigger search, program completely freezes and can only be closed with xkill.

The core dump file is 1.7GB, much bigger than I expected. Does that seem right?

It's not a major hassle, I can workaround it by using CTRL + F, but I often prefer to use the other search option.

**Comment by SteveMcNeill** [comment] 2022-05-16 12:17
1.7GB?  That doesn't seem possible at all to me.  I just downloaded, unpacked, and set-up a fresh version of the repo -- and the whole thing comes in at being only 1.1GB in size.

Did you extract the folder over an old copy you had on your drive, perhaps?  IF so, then that's most likely the issue.  Extract to a new folder and see what happens.

I'm completely at a loss otherwise in trying to explain how you can get a core dump larger than all of QB64 itself.

**Comment by loopy750** [comment] 2022-05-16 14:11
Thanks for creating the dump file.

I just realised it can also be reproduced in Windows 11. And yes, 1 cpu thread is maxed out at 100% and I need to use Task Manager to close it.

**Comment by mkilgore** [comment] 2022-05-17 01:54
I believe I figured it out :) Around line 11150 in `./source/qb64.bas` there is logic that does a `DO-LOOP` through each line in `./internal/temp/searched.bin`:
```basic
    DO WHILE LEN(a$)
        ai = INSTR(a$, CRLF)
        IF ai THEN
            f$ = LEFT$(a$, ai - 1): IF ai = LEN(a$) - 1 THEN a$ = "" ELSE a$ = RIGHT$(a$, LEN(a$) - ai - 3)
            ln = ln + 1
            REDIM _PRESERVE SearchHistory(1 TO ln)
            SearchHistory(ln) = f$
        END IF
    LOOP
```

I'm pretty sure the issue is that on Linux the `./internal/temp/searched.bin` that comes from the repository (so, the one you have the very first time you open QB64) contains Linux line endings due to `git` doing a conversion. When that happens there is no CRLF but the file is non-zero length, so it just loops forever. Thankfully I think there's a variety of simple ways to make sure it cannot loop infinitely.

`2.0.2` from `QB64Team/qb64` has the same code and can be coaxed into hitting the loop if you edit the `searched.bin` file, but it does not ship with one by default so that's how it avoids the issue.

**Comment by mkilgore** [comment] 2022-05-17 13:55
Yeah I think that makes sense with what I found :) The `qb64_win-x64.7z` should have proper Windows line endings, but the `Source code (zip)` and `qb64_lnx.tar.gz` will have LF line endings and thus hit the bug.

**Comment by SteveMcNeill** [comment] 2022-05-20 21:14
Closing this as I think it's fixed now and nobody has reported any further issues with it.  If necessary, we can always reopen this issue again.

**Closed by SteveMcNeill** 2022-05-20 21:14 UTC
Labels: bug
